# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = C:/Users/Dell/Downloads/cmake-3.23.0-rc1-windows-x86_64/bin/cmake.exe

# The command to remove a file.
RM = C:/Users/Dell/Downloads/cmake-3.23.0-rc1-windows-x86_64/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:/Users/Dell/Downloads/!mcw/assignment

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:/Users/Dell/Downloads/!mcw/assignment

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	C:/Users/Dell/Downloads/cmake-3.23.0-rc1-windows-x86_64/bin/cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:/Users/Dell/Downloads/cmake-3.23.0-rc1-windows-x86_64/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/Dell/Downloads/!mcw/assignment/CMakeFiles C:/Users/Dell/Downloads/!mcw/assignment//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/Dell/Downloads/!mcw/assignment/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named outp

# Build rule for target.
outp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 outp
.PHONY : outp

# fast build rule for target.
outp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/outp.dir/build.make CMakeFiles/outp.dir/build
.PHONY : outp/fast

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/outp.dir/build.make CMakeFiles/outp.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/outp.dir/build.make CMakeFiles/outp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/outp.dir/build.make CMakeFiles/outp.dir/main.cpp.s
.PHONY : main.cpp.s

symtable_link.obj: symtable_link.cpp.obj
.PHONY : symtable_link.obj

# target to build an object file
symtable_link.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/outp.dir/build.make CMakeFiles/outp.dir/symtable_link.cpp.obj
.PHONY : symtable_link.cpp.obj

symtable_link.i: symtable_link.cpp.i
.PHONY : symtable_link.i

# target to preprocess a source file
symtable_link.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/outp.dir/build.make CMakeFiles/outp.dir/symtable_link.cpp.i
.PHONY : symtable_link.cpp.i

symtable_link.s: symtable_link.cpp.s
.PHONY : symtable_link.s

# target to generate assembly for a file
symtable_link.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/outp.dir/build.make CMakeFiles/outp.dir/symtable_link.cpp.s
.PHONY : symtable_link.cpp.s

symtable_test.obj: symtable_test.cpp.obj
.PHONY : symtable_test.obj

# target to build an object file
symtable_test.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/outp.dir/build.make CMakeFiles/outp.dir/symtable_test.cpp.obj
.PHONY : symtable_test.cpp.obj

symtable_test.i: symtable_test.cpp.i
.PHONY : symtable_test.i

# target to preprocess a source file
symtable_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/outp.dir/build.make CMakeFiles/outp.dir/symtable_test.cpp.i
.PHONY : symtable_test.cpp.i

symtable_test.s: symtable_test.cpp.s
.PHONY : symtable_test.s

# target to generate assembly for a file
symtable_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/outp.dir/build.make CMakeFiles/outp.dir/symtable_test.cpp.s
.PHONY : symtable_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... outp"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... symtable_link.obj"
	@echo "... symtable_link.i"
	@echo "... symtable_link.s"
	@echo "... symtable_test.obj"
	@echo "... symtable_test.i"
	@echo "... symtable_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

